version: 1.0
provider:
  name: openfaas
  gateway: http://<hostname>:31112
functions:
  product-photos-1-microbench:
    lang: node10-express
    handler: ./product-photos-1-microbench
    image: dsirone/product-photos-1-microbench:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PHOTO_ASSIGNMENTS_NAME: 'photoAssignmentTable'
      TABLE_STORED_PHOTOS_NAME: 'storedPhotosTable'
      HOST: 'mysql.openfaas-fn.svc.cluster.local'
      USER: 'abc'
      PASS: 'xyz'
      #http_proxy: 'http://127.0.0.1:8082'
      #https_proxy: 'http://127.0.0.1:8082'
      #annotations:
      #com.openfaas.profile: test
