version: 1.0
provider:
  name: openfaas
  gateway: http://node4.netes2.cs799-serverless-pg0.wisc.cloudlab.us:31112
functions:
  trapeze-product-photos-3-receive:
    lang: node10-express
    handler: ./product-photos-3-receive
    image: dsirone/trapeze-product-photos-3-receive:latest
    read_timeout: 1000s # seconds
    write_timeout: 1000s # seconds
    exec_timeout: 1000s # disable
    #write_debug: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PHOTO_ASSIGNMENTS_NAME: 'photoAssignmentTable'
      TABLE_STORED_PHOTOS_NAME: 'storedPhotosTable'
      HOST: 'mysql.openfaas-fn.svc.cluster.local'
      USER: 'abc'
      PASS: 'xyz'
    annotations:
      com.openfaas.profile: test
