version: 1.0
provider:
  name: openfaas
  gateway: http://<gateway>:31112
functions:
  product-photos-3-receive:
    lang: node10-express
    handler: ./product-photos-3-receive
    image: dsirone/gvisor-product-photos-3-receive:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PHOTO_ASSIGNMENTS_NAME: 'photoAssignmentTable'
      TABLE_STORED_PHOTOS_NAME: 'storedPhotosTable'
      HOST: 'mysql.openfaas-fn.svc.cluster.local'
      USER: 'abc'
      PASS: 'xyz'
      #annotations:
      #com.openfaas.profile: test
