version: 1.0
provider:
  name: openfaas
  gateway: http://node4.netes2.cs799-serverless-pg0.wisc.cloudlab.us:31112
functions:
  product-purchase-1-authenticate:
    lang: node10-express
    handler: ./product-purchase-1-authenticate
    image: dsirone/product-purchase-1authenticate:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_AUTHENTICATION_NAME: 'authenticationName'
      HOST: 'mysql.openfaas-fn.svc.cluster.local'
      USER: 'abc'
      PASS: 'xyz'
    annotations:
      com.openfaas.profile: test
