version: 1.0
provider:
  name: openfaas
  gateway: http://node4.netes2.cs799-serverless-pg0.wisc.cloudlab.us:31112
functions:
  trapeze-product-photos-2-message:
    lang: node10-express
    handler: ./product-photos-2-message
    image: dsirone/trapeze-product-photos-2-message:latest
    annotations:
      com.openfaas.profile: test
